/**
 * Download the three self-hosted families once, into public/fonts/, and generate
 * src/styles/fonts.css.
 *
 * Fonts are committed rather than fetched at build time, so the build is
 * deterministic and needs no network. Re-run this only to change a family,
 * a weight or a subset:
 *
 *   npx tsx scripts/fetch-fonts.ts
 *
 * All three families are SIL Open Font License 1.1 and may be self-hosted.
 */
import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { resolve } from 'node:path';
import { fromBuffer } from '@capsizecss/unpack';
import arial from '@capsizecss/metrics/arial';
import timesNewRoman from '@capsizecss/metrics/timesNewRoman';
import courierNew from '@capsizecss/metrics/courierNew';

const ROOT = resolve(import.meta.dirname, '..');
const OUT_DIR = resolve(ROOT, 'public/fonts');
const UA =
  'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36';

/** English-only site, so only the Latin subsets are downloaded. */
const SUBSETS = new Set(['latin', 'latin-ext']);

/**
 * Glyphs the display and mono families are ever asked to render. Inter Tight carries
 * the body copy and takes the whole Latin subset; the other two only set headings,
 * metrics and labels, so requesting them glyph-by-glyph turns ~97 kB into ~20 kB on
 * the critical path. Anything outside this set falls back to the metric-matched
 * system font rather than rendering wrong.
 */
/** Headings only: letters, digits and the punctuation a title can contain. */
const DISPLAY_GLYPHS =
  'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789' +
  ' .,;:!?&-\'"()/' +
  'ÄÖÜäöüßÉéÀàÇç' +
  '—–';

/** Metrics, kickers, code and stack tags, so the symbol set has to be wider. */
const MONO_GLYPHS = DISPLAY_GLYPHS + '@#%*[]{}<>=+_|~$^`\\' + '→←↑↓±·×÷≤≥°⌘…';

const FAMILIES: { slug: string; family: string; query: string; text?: string }[] = [
  { slug: 'inter-tight', family: 'Inter Tight', query: 'Inter+Tight:wght@400;500;600;700' },
  // Instrument Serif rather than the spec's Fraunces or Newsreader: both of those are
  // variable fonts whose axis data keeps them near 45-80 kB even glyph-subset, and the
  // browser fetches a display face at VeryHigh priority - ahead of the hero image - so
  // they cost the LCP budget directly. Instrument Serif is a static display serif at
  // ~15 kB. Measured, not assumed: see the note in README.md.
  {
    slug: 'instrument-serif',
    family: 'Instrument Serif',
    query: 'Instrument+Serif',
    text: DISPLAY_GLYPHS,
  },
  {
    slug: 'jetbrains-mono',
    family: 'JetBrains Mono',
    query: 'JetBrains+Mono:wght@400;500;700',
    text: MONO_GLYPHS,
  },
];

interface Face {
  subset: string;
  weight: string;
  style: string;
  url: string;
  unicodeRange: string;
  file: string;
}

await mkdir(OUT_DIR, { recursive: true });
const css: string[] = [
  '/* Generated by scripts/fetch-fonts.ts - do not edit by hand.',
  '   Inter Tight, Instrument Serif and JetBrains Mono are SIL Open Font License 1.1.',
  '   See public/fonts/OFL.txt. */',
  '',
];
let downloaded = 0;
/** First file written per family, used below to read real vertical metrics. */
const metricsFileBySlug: Record<string, string> = {};

for (const { slug, family, query, text } of FAMILIES) {
  const url =
    `https://fonts.googleapis.com/css2?family=${query}&display=swap` +
    (text ? `&text=${encodeURIComponent(text)}` : '');
  const res = await fetch(url, { headers: { 'user-agent': UA } });
  if (!res.ok) throw new Error(`${family}: HTTP ${res.status}`);
  const sheet = await res.text();

  /**
   * Two shapes come back. Without `text` Google emits one @font-face per subset,
   * each preceded by a `/* subset *\/` comment. With `text` it emits one face per
   * weight with no comment - that is already the only subset we want.
   */
  const faces: Face[] = [];
  for (const m of sheet.matchAll(/(?:\/\*\s*([\w-]+)\s*\*\/\s*)?@font-face\s*\{([^}]*)\}/g)) {
    const [, named, block] = m;
    const subset = named ?? 'custom';
    if (!text && !SUBSETS.has(subset)) continue;
    const src = block.match(/src:\s*url\((https:[^)]+)\)/)?.[1];
    const weight = block.match(/font-weight:\s*([^;]+);/)?.[1].trim();
    const style = block.match(/font-style:\s*([^;]+);/)?.[1].trim() ?? 'normal';
    const unicodeRange = block.match(/unicode-range:\s*([^;]+);/)?.[1].trim();
    if (!src || !weight || !unicodeRange) continue;
    faces.push({
      subset,
      weight,
      style,
      url: src,
      unicodeRange,
      file: `${slug}-${weight.replace(/\s+/g, '_')}-${style}-${subset}.woff2`,
    });
  }
  if (!faces.length) throw new Error(`${family}: no faces parsed`);

  /**
   * These are variable fonts: Google serves one file per subset and declares it once
   * per requested weight. Map url -> filename so repeated weights reference the file
   * that was actually written instead of a name that does not exist.
   */
  const fileByUrl = new Map<string, string>();
  for (const face of faces) {
    const existing = fileByUrl.get(face.url);
    if (existing) {
      face.file = existing;
    } else {
      const bin = await fetch(face.url, { headers: { 'user-agent': UA } });
      if (!bin.ok) throw new Error(`${face.file}: HTTP ${bin.status}`);
      await writeFile(resolve(OUT_DIR, face.file), Buffer.from(await bin.arrayBuffer()));
      fileByUrl.set(face.url, face.file);
      metricsFileBySlug[slug] ??= face.file;
      downloaded++;
    }
    css.push(
      '@font-face {',
      `  font-family: '${family}';`,
      `  font-style: ${face.style};`,
      `  font-weight: ${face.weight};`,
      /**
       * `optional`, not `swap`. With metric-matched fallbacks a swap still changes the
       * line COUNT of a large heading, which moves the whole hero block - measured at
       * CLS 0.233. `optional` renders the fallback and never swaps mid-load, so the
       * layout cannot shift; the real face appears from the HTTP cache on any later
       * view. Inter Tight is preloaded so it usually wins the first-paint race anyway.
       */
      '  font-display: optional;',
      `  src: url('/fonts/${face.file}') format('woff2');`,
      `  unicode-range: ${face.unicodeRange};`,
      '}',
      '',
    );
  }
  console.log(`${family}: ${faces.length} faces (${fileByUrl.size} files)`);
}

/**
 * Metric-matched fallbacks. Each family gets a synthetic @font-face over a local
 * system font, scaled so that a line of fallback text occupies the same box as the
 * real font. This is what keeps CLS near zero while the woff2 is still in flight.
 */
const FALLBACKS: Record<string, { local: string; metrics: typeof arial }> = {
  'Inter Tight': { local: 'Arial', metrics: arial },
  'Instrument Serif': { local: 'Times New Roman', metrics: timesNewRoman },
  'JetBrains Mono': { local: 'Courier New', metrics: courierNew },
};

css.push(
  '/* Metric-matched fallbacks - keep the fallback line box the same size as the real font. */',
  '',
);

const pct = (n: number) => `${(n * 100).toFixed(3)}%`;

for (const { slug, family } of FAMILIES) {
  const buf = await readFile(resolve(OUT_DIR, metricsFileBySlug[slug]));
  const web = await fromBuffer(buf);
  const { local, metrics: fb } = FALLBACKS[family];

  /**
   * Capsize's formula. `size-adjust` matches the average glyph WIDTH of the fallback
   * to the real font - without it the line box is the right height but the wrong
   * length, and the swap reflows every heading. The vertical overrides are then
   * divided by that adjustment so the height stays right too.
   */
  const sizeAdjust = web.xWidthAvg / web.unitsPerEm / (fb.xWidthAvg / fb.unitsPerEm);
  css.push(
    '@font-face {',
    `  font-family: '${family} fallback';`,
    `  src: local('${local}');`,
    `  size-adjust: ${pct(sizeAdjust)};`,
    `  ascent-override: ${pct(web.ascent / web.unitsPerEm / sizeAdjust)};`,
    `  descent-override: ${pct(Math.abs(web.descent) / web.unitsPerEm / sizeAdjust)};`,
    `  line-gap-override: ${pct(web.lineGap / web.unitsPerEm / sizeAdjust)};`,
    '}',
    '',
  );
  console.log(`${family}: fallback ${local}, size-adjust ${pct(sizeAdjust)}`);
}

await writeFile(resolve(ROOT, 'src/styles/fonts.css'), css.join('\n'));
console.log(`wrote ${downloaded} woff2 files and src/styles/fonts.css`);
