/**
 * Download the three self-hosted families once, into public/fonts/, and generate
 * src/styles/fonts.css.
 *
 * Fonts are committed rather than fetched at build time, so the build is
 * deterministic and needs no network. Re-run this only to change a family,
 * a weight or a subset:
 *
 *   npx tsx scripts/fetch-fonts.ts
 *
 * All three families are SIL Open Font License 1.1 and may be self-hosted.
 */
import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { resolve } from 'node:path';
import { fromBuffer } from '@capsizecss/unpack';

const ROOT = resolve(import.meta.dirname, '..');
const OUT_DIR = resolve(ROOT, 'public/fonts');
const UA =
  'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36';

/** English-only site, so only the Latin subsets are downloaded. */
const SUBSETS = new Set(['latin', 'latin-ext']);

const FAMILIES = [
  { slug: 'inter-tight', family: 'Inter Tight', query: 'Inter+Tight:wght@400;500;600;700' },
  { slug: 'fraunces', family: 'Fraunces', query: 'Fraunces:opsz,wght@9..144,400;9..144,600' },
  { slug: 'jetbrains-mono', family: 'JetBrains Mono', query: 'JetBrains+Mono:wght@400;500;700' },
];

interface Face {
  subset: string;
  weight: string;
  style: string;
  url: string;
  unicodeRange: string;
  file: string;
}

await mkdir(OUT_DIR, { recursive: true });
const css: string[] = [
  '/* Generated by scripts/fetch-fonts.ts - do not edit by hand.',
  '   Inter Tight, Fraunces and JetBrains Mono are SIL Open Font License 1.1.',
  '   See public/fonts/OFL.txt. */',
  '',
];
let downloaded = 0;

for (const { slug, family, query } of FAMILIES) {
  const res = await fetch(`https://fonts.googleapis.com/css2?family=${query}&display=swap`, {
    headers: { 'user-agent': UA },
  });
  if (!res.ok) throw new Error(`${family}: HTTP ${res.status}`);
  const sheet = await res.text();

  const faces: Face[] = [];
  const blocks = sheet.split('/*').slice(1);
  for (const block of blocks) {
    const subset = block.slice(0, block.indexOf('*/')).trim();
    if (!SUBSETS.has(subset)) continue;
    const url = block.match(/src:\s*url\((https:[^)]+)\)/)?.[1];
    const weight = block.match(/font-weight:\s*([^;]+);/)?.[1].trim();
    const style = block.match(/font-style:\s*([^;]+);/)?.[1].trim() ?? 'normal';
    const unicodeRange = block.match(/unicode-range:\s*([^;]+);/)?.[1].trim();
    if (!url || !weight || !unicodeRange) continue;
    faces.push({
      subset,
      weight,
      style,
      url,
      unicodeRange,
      file: `${slug}-${weight.replace(/\s+/g, '_')}-${subset}.woff2`,
    });
  }
  if (!faces.length) throw new Error(`${family}: no latin faces parsed`);

  const seen = new Set<string>();
  for (const face of faces) {
    if (!seen.has(face.url)) {
      seen.add(face.url);
      const bin = await fetch(face.url, { headers: { 'user-agent': UA } });
      if (!bin.ok) throw new Error(`${face.file}: HTTP ${bin.status}`);
      await writeFile(resolve(OUT_DIR, face.file), Buffer.from(await bin.arrayBuffer()));
      downloaded++;
    }
    css.push(
      '@font-face {',
      `  font-family: '${family}';`,
      `  font-style: ${face.style};`,
      `  font-weight: ${face.weight};`,
      '  font-display: swap;',
      `  src: url('/fonts/${face.file}') format('woff2');`,
      `  unicode-range: ${face.unicodeRange};`,
      '}',
      '',
    );
  }
  console.log(`${family}: ${faces.length} faces (${seen.size} files)`);
}

/**
 * Metric-matched fallbacks. Each family gets a synthetic @font-face over a local
 * system font, scaled so that a line of fallback text occupies the same box as the
 * real font. This is what keeps CLS near zero while the woff2 is still in flight.
 */
const FALLBACK_LOCALS: Record<string, string[]> = {
  'Inter Tight': ['Arial', 'Helvetica', 'Roboto'],
  Fraunces: ['Times New Roman', 'Georgia'],
  'JetBrains Mono': ['Courier New', 'Menlo'],
};

css.push('/* Metric-matched fallbacks - keep the fallback line box the same size as the real font. */', '');

for (const { slug, family } of FAMILIES) {
  const buf = await readFile(resolve(OUT_DIR, `${slug}-400-latin.woff2`));
  const m = await fromBuffer(buf);
  const ascent = (m.ascent / m.unitsPerEm).toFixed(4);
  const descent = (Math.abs(m.descent) / m.unitsPerEm).toFixed(4);
  const lineGap = (m.lineGap / m.unitsPerEm).toFixed(4);
  for (const local of FALLBACK_LOCALS[family]) {
    css.push(
      '@font-face {',
      `  font-family: '${family} fallback';`,
      `  src: local('${local}');`,
      `  ascent-override: ${Number(ascent) * 100}%;`,
      `  descent-override: ${Number(descent) * 100}%;`,
      `  line-gap-override: ${Number(lineGap) * 100}%;`,
      '  size-adjust: 100%;',
      '}',
      '',
    );
  }
  console.log(`${family}: fallback metrics asc ${ascent} desc ${descent} gap ${lineGap}`);
}

await writeFile(resolve(ROOT, 'src/styles/fonts.css'), css.join('\n'));
console.log(`wrote ${downloaded} woff2 files and src/styles/fonts.css`);
